from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from PySide6.QtWidgets import QCheckBox, QLabel, QWidget

    from gui.widgets import Card


class TabBuilderHost(Protocol):
    inputs: dict[str, dict]
    adv_rows: dict[str, dict]
    adv_frames: list

    def _build_advanced_flags_card(self, tab_key: str) -> "Card": ...
    def _add_browse_action(self, line_edit, title: str) -> None: ...
    def _make_field_error_label(self) -> "QLabel": ...
    def _register_field_error_label(
        self, tab: str, key: str, lbl: "QLabel"
    ) -> None: ...
    def _bind_field_error_clear(self, tab: str, key: str, widget) -> None: ...
    def _wrap_with_field_error(self, tab: str, key: str, widget) -> "QWidget": ...
    def _add_ssl_skip_row(self, form, tab_dict, **kw) -> "QCheckBox": ...
